spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=content-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${CONTENT_SERVICE_URL:http://localhost:3000}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/posts/**

spring.cloud.gateway.server.webmvc.routes[1].id=moderation-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${MODERATION_SERVICE_URL:http://localhost:8000}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/moderate/**

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_W9UJRATat

cognito.client-id=${COGNITO_CLIENT_ID}
cognito.client-secret=${COGNITO_CLIENT_SECRET}
cognito.token-uri=${COGNITO_TOKEN_URI}